export { default as TabsWrapper } from './TabsWrapper.vue'
export { default as TabLabels } from './TabLabels.vue'
export { default as TabLabel } from './TabLabel.vue'
export { default as TabPanels } from './TabPanels.vue'
export { default as TabPanel } from './TabPanel.vue'
